version: '3'
#volumes:
#  postgis-data:

services:

  db:
    image: kartoza/postgis:10.0-2.4
#    volumes:
#      - 'postgis-data:/var/lib/postgresql'
    environment:
      - POSTGRES_DB=comptages
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 25432:5432
    restart: "no"