version: '3'
services:
  qgis_tester:
    build: 
        context: ..
        dockerfile: ./.docker/Dockerfile
    container_name: qgis_tester 
    tty: true
    volumes:
      - ./tests:/tests
    #links:
    #  - db:comptages-db

  comptages-db:
    image: kartoza/postgis:10.0-2.4
    environment:
      - POSTGRES_DB=comptages
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5432:5432
    restart: "no"


